trigger:
- master

variables:
- group: production

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: UseNode@1
      inputs:
        version: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'