trigger:
- master

variables:
- group: prod

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: UseNode@1
      inputs:
        version: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'

    - task: CopyFiles@2
      displayName: 'Copy files to build directory'
      inputs:
        contents: |
          dist/**
        targetFolder: '$(Pipeline.Workspace)/build'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(Pipeline.Workspace)/build'
        archiveType: 'tar'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
        replaceExistingArchive: true
        includeRootFolder: false

    - task: PublishPipelineArtifact@1
      displayName: 'Publish artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
        artifactName: 'drop'